# Generated by Django 5.0.4 on 2024-04-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='message',
        ),
    ]
