# Generated by Django 5.0.3 on 2024-04-20 19:03

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_anonymous_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
