# Generated by Django 5.0.3 on 2024-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
