# Generated by Django 5.0.3 on 2024-04-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_folder_user'),
        ('task', '0002_alter_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isTeam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, default='All', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='folder.folder'),
        ),
    ]
