# Generated by Django 5.0.3 on 2024-04-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_folder_user'),
        ('task', '0004_remove_task_isteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='folder.folder'),
        ),
    ]
