# Generated by Django 5.0.4 on 2025-04-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_alter_folder_user'),
        ('task', '0005_alter_task_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, db_column='folder_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='folder.folder'),
        ),
    ]
